export const propertiesData = {
  Noida: [
    {
      id: 1,
      status: "New Launch",
      name: "Edge Expert Tropical Isle",
      location: "Sector 146, Noida",
      type: "3 & 4 BHK Premium Homes",
      price: "₹ 3.00 Cr* Onwards",
      details: [
        "Project Area: 12.4 Acres",
        "Early Bird Discount: ₹ 2 Lacs*",
        "Luxury Amenities Included",
      ],
      image:
        "https://i.pinimg.com/736x/fe/3f/ec/fe3fecad796aa7b030e4e7cdb3d93da9.jpg",
    },
    {
      id: 2,
      status: "Under Construction",
      name: "Edge Expert Woods",
      location: "Sector 43, Noida",
      type: "2, 3 & 4 BHK Apartments",
      price: "₹ 2.2 Cr* Onwards",
      details: [
        "Forest-themed Living",
        "Close to Noida Golf Course",
        "Premium Clubhouse Facilities",
      ],
      image:
        "https://i.pinimg.com/1200x/91/9c/48/919c4831fade74cb3d0e1b37e5ef29e5.jpg",
    },
    {
      id: 3,
      status: "Ready to Move",
      name: "Edge Expert Nest",
      location: "Sector 150, Noida",
      type: "2, 3 & 4 BHK Homes",
      price: "₹ 1.5 Cr* Onwards",
      details: [
        "Smart Security Systems",
        "Adjacent to Sports City",
        "Modern Clubhouse",
      ],
      image:
        "https://i.pinimg.com/1200x/5c/ad/ea/5cadea10efad90db088459fd5a3b4a3b.jpg",
    },
    {
      id: 4,
      status: "New Launch",
      name: "Edge Expert Palm Retreat",
      location: "Sector 150, Noida",
      type: "2 & 3 BHK Resort Residences",
      price: "₹ 1.8 Cr* Onwards",
      details: [
        "Resort Style Living",
        "Low-Density Project",
        "Sky Walk Amenities",
      ],
      image:
        "https://i.pinimg.com/736x/26/fd/0f/26fd0f6e5d22a17435379ec5239f9c3b.jpg",
    },
  ],

  Delhi: [
    {
      id: 5,
      status: "Ready to Move",
      name: "Edge Expert Prima",
      location: "Okhla Phase 1, Delhi",
      type: "2 & 3 BHK Premium Residences",
      price: "₹ 4.8 Cr* Onwards",
      details: [
        "Italian Marble Flooring",
        "Clubhouse by Gauri Khan",
        "5-Star Concierge Services",
      ],
      image:
        "https://i.pinimg.com/1200x/88/d7/97/88d79704ea5f470ffa31d7cc19f019d7.jpg",
    },
    {
      id: 6,
      status: "Under Construction",
      name: "Edge Expert South Estate",
      location: "Okhla, South Delhi",
      type: "3 BHK Apartments",
      price: "₹ 5.5 Cr* Onwards",
      details: ["Luxurious Spa", "24x7 Security", "Excellent Connectivity"],
      image:
        "https://i.pinimg.com/1200x/79/37/7f/79377f1a107713b47c70dccae00e2474.jpg",
    },
    {
      id: 7,
      status: "New Launch",
      name: "Edge Expert Connaught One",
      location: "Connaught Place, Delhi",
      type: "3 & 4 BHK Ultra-Luxury",
      price: "₹ 17.5 Cr* Onwards",
      details: [
        "Central Delhi Address",
        "Limited Edition Residences",
        "5-Star Hospitality",
      ],
      image:
        "https://i.pinimg.com/1200x/42/00/c2/4200c2f960b1d96e332f92e545b132fc.jpg",
    },
    {
      id: 8,
      status: "Ready to Move",
      name: "Edge Expert One Residency",
      location: "Dwarka, Delhi",
      type: "2 & 3 BHK Residences",
      price: "₹ 2.8 Cr* Onwards",
      details: ["Airport View", "Smart Home Features", "Gym & Pool"],
      image:
        "https://www.nyatigroup.com/assets/images/enchante_i/Enchante-I_1_hpb.jpg",
    },
  ],

  Mumbai: [
    {
      id: 9,
      status: "New Launch",
      name: "Edge Expert Ascend",
      location: "Kolshet Road, Thane",
      type: "2 & 3 BHK Homes",
      price: "₹ 1.4 Cr* Onwards",
      details: ["75,000 sq.ft. Clubhouse", "Sports Arena", "River View Homes"],
      image:
        "https://i.pinimg.com/1200x/cc/5a/e9/cc5ae909011cec7b493641287d858196.jpg",
    },
    {
      id: 10,
      status: "Ready to Move",
      name: "Edge Expert Tranquil",
      location: "Kandivali East, Mumbai",
      type: "1, 2 & 3 BHK Apartments",
      price: "₹ 1.9 Cr* Onwards",
      details: [
        "Sky Decks & Infinity Pool",
        "Western Express Connectivity",
        "Sea & City Views",
      ],
      image:
        "https://i.pinimg.com/1200x/c0/c6/a2/c0c6a2002608e58eab4d33bcfffffc08.jpg",
    },
    {
      id: 11,
      status: "Under Construction",
      name: "Edge Expert Urban Park",
      location: "Chandivali, Mumbai",
      type: "2 & 3 BHK Residences",
      price: "₹ 1.7 Cr* Onwards",
      details: [
        "Lush Green Environment",
        "Yoga Deck & Sky Lounge",
        "Modern Interiors",
      ],
      image:
        "https://i.pinimg.com/1200x/bb/14/c9/bb14c9e5d66799ce9104c7e06942e6d9.jpg",
    },
    {
      id: 12,
      status: "New Launch",
      name: "Edge Expert Bliss",
      location: "Chembur, Mumbai",
      type: "2 & 3 BHK Residences",
      price: "₹ 2.3 Cr* Onwards",
      details: [
        "Sea Facing Apartments",
        "Luxury Interiors",
        "24x7 Concierge Service",
      ],
      image: "https://i.pinimg.com/1200x/3d/88/40/3d88409c5def8373c5f813855522625d.jpg",
    },
  ],

  Pune: [
    {
      id: 13,
      status: "Ready to Move",
      name: "Edge Expert Rejuve",
      location: "Keshav Nagar, Pune",
      type: "2 & 3 BHK Residences",
      price: "₹ 1.2 Cr* Onwards",
      details: ["25+ Lifestyle Amenities", "Green Living Concept", "Close to IT Hubs"],
      image:
        "https://i.pinimg.com/1200x/75/01/c5/7501c5e170c822f5e91e29f9eba7fb89.jpg",
    },
    {
      id: 14,
      status: "Under Construction",
      name: "Edge Expert Hill Retreat",
      location: "Baner-Mahalunge, Pune",
      type: "2 & 3 BHK Apartments",
      price: "₹ 95 Lacs* Onwards",
      details: ["Riverfront Living", "Spa & Wellness Center", "Sports Facilities"],
      image:
        "https://i.pinimg.com/736x/bc/a7/cc/bca7cc732712d90130e5791a7e13d191.jpg",
    },
    {
      id: 15,
      status: "New Launch",
      name: "Edge Expert Parkridge",
      location: "Manjari, Pune",
      type: "1, 2 & 3 BHK Residences",
      price: "₹ 70 Lacs* Onwards",
      details: ["Urban Living", "Open Green Spaces", "Family-Friendly Design"],
      image: "https://i.pinimg.com/736x/2d/db/d3/2ddbd33733b45ab0779eef701a0b8168.jpg",
    },
    {
      id: 16,
      status: "Ready to Move",
      name: "Edge Expert Hillside 3",
      location: "Mahalunge, Pune",
      type: "1, 2 & 3 BHK Homes",
      price: "₹ 75 Lacs* Onwards",
      details: ["Urban Township Project", "Hill Views", "High-Rise Towers"],
      image:
        "https://www.godrejproperties.com/_next/image?url=https%3A%2F%2Fd3gq2merok8n5r.cloudfront.net%2Fmedia%2Fproject%2Fhillside3-pune.jpg&w=1080&q=75",
    },
  ],

  Bangalore: [
    {
      id: 17,
      status: "New Launch",
      name: "Edge Expert Athena",
      location: "Indiranagar, Bangalore",
      type: "3 & 4 BHK Luxury Homes",
      price: "₹ 2.5 Cr* Onwards",
      details: ["European Architecture", "Clubhouse with Pool", "Prime Location"],
      image:
        "https://i.pinimg.com/736x/c5/ce/18/c5ce180059a79d4938727aeacba073ba.jpg",
    },
    {
      id: 18,
      status: "Under Construction",
      name: "Edge Expert Ananda",
      location: "Aerospace Park, Bangalore",
      type: "1, 2 & 3 BHK Homes",
      price: "₹ 60 Lacs* Onwards",
      details: ["Smart Homes", "Close to Airport", "Premium Amenities"],
      image:
        "https://i.pinimg.com/736x/1b/5f/f7/1b5ff7607ffbee01d1d9a7637b31507e.jpg",
    },
    {
      id: 19,
      status: "Ready to Move",
      name: "Edge Expert Eternity",
      location: "Kanakapura Road, Bangalore",
      type: "2 & 3 BHK Apartments",
      price: "₹ 1.3 Cr* Onwards",
      details: ["Heritage Inspired Architecture", "Lush Courtyards", "Gym & Pool"],
      image: "https://i.pinimg.com/736x/99/b7/0b/99b70b38db48dcdd7465473203b059c6.jpg",
    },
    {
      id: 20,
      status: "New Launch",
      name: "Edge Expert Park Retreat",
      location: "Sarjapur Road, Bangalore",
      type: "1, 2 & 3 BHK Residences",
      price: "₹ 90 Lacs* Onwards",
      details: ["Smart Living Spaces", "Clubhouse", "Sports Arena"],
      image: "https://i.pinimg.com/736x/26/44/f6/2644f64d0c7c22855f4fa151d137a7e4.jpg",
    },
  ],

  Chennai: [
    {
      id: 21,
      status: "New Launch",
      name: "Edge Expert Azure",
      location: "OMR, Chennai",
      type: "2 & 3 BHK Apartments",
      price: "₹ 90 Lacs* Onwards",
      details: ["Sea View Residences", "Rooftop Lounge", "Premium Interiors"],
      image: "https://i.pinimg.com/1200x/84/a0/af/84a0afacb3325f4d432978385ccd63a9.jpg",
    },
    {
      id: 22,
      status: "Under Construction",
      name: "Edge Expert Palm Grove",
      location: "Poonamallee, Chennai",
      type: "2 & 3 BHK Homes",
      price: "₹ 75 Lacs* Onwards",
      details: ["Peaceful Living", "Spacious Layout", "24x7 Security"],
      image: "https://i.pinimg.com/736x/bb/bb/8d/bbbb8d2b822b107d87253eed0a743103.jpg",
    },
    {
      id: 23,
      status: "Ready to Move",
      name: "Edge Expert Serenity",
      location: "ECR, Chennai",
      type: "3 & 4 BHK Villas",
      price: "₹ 2.2 Cr* Onwards",
      details: ["Private Garden", "Swimming Pool", "Luxury Amenities"],
      image: "https://i.pinimg.com/736x/73/38/23/7338234e1ba51d1a475f60ab64cfb9a8.jpg",
    },
    {
      id: 24,
      status: "New Launch",
      name: "Edge Expert Sunrise",
      location: "Perumbakkam, Chennai",
      type: "2 & 3 BHK Apartments",
      price: "₹ 85 Lacs* Onwards",
      details: ["Eco-friendly Design", "Open Green Spaces", "Modern Gym"],
      image: "https://www.nyatigroup.com/assets/images/enchante_i/Enchante-I_1_hpb.jpg",
    },
  ],

  Hyderabad: [
    {
      id: 25,
      status: "Ready to Move",
      name: "Edge Expert Habitat",
      location: "Kondapur, Hyderabad",
      type: "2, 3 & 4 BHK Apartments",
      price: "₹ 1.3 Cr* Onwards",
      details: ["Gated Community", "Smart Security", "Swimming Pool"],
      image: "https://propertydotcom.co.in/public/property/property1647069783uqrkvi3f.jpg",
    },
    {
      id: 26,
      status: "Under Construction",
      name: "Edge Expert Reserve",
      location: "Shamshabad, Hyderabad",
      type: "Luxury Plots",
      price: "₹ 80 Lacs* Onwards",
      details: ["Green Living", "Wide Roads", "Modern Amenities"],
      image: "https://www.buyindiahomes.com/public/uploads/properties/276/20200304033129_Mantri-VantagecityT.jpg",
    },
    {
      id: 27,
      status: "New Launch",
      name: "Edge Expert Infinity",
      location: "Gachibowli, Hyderabad",
      type: "3 & 4 BHK Apartments",
      price: "₹ 2.4 Cr* Onwards",
      details: ["Sky Lounge", "Work-from-home Pods", "Green Open Spaces"],
      image: "https://www.propertycrow.com/photos/2913/photo-21601.jpeg",
    },
    {
      id: 28,
      status: "New Launch",
      name: "Edge Expert Nirvana",
      location: "Kokapet, Hyderabad",
      type: "2 & 3 BHK Residences",
      price: "₹ 1.5 Cr* Onwards",
      details: ["Premium Interiors", "Close to Financial District", "Luxury Amenities"],
      image: "https://www.buyindiahomes.com/public/uploads/properties/25/20190509063409_CoverT.jpg",
    },
  ],

  Gurugram: [
    {
      id: 29,
      status: "New Launch",
      name: "Edge Expert Air",
      location: "Sector 85, Gurugram",
      type: "2, 3 & 4 BHK Residences",
      price: "₹ 1.8 Cr* Onwards",
      details: ["Pure Air Zone", "Smart Home Features", "Prime Location"],
      image: "https://teja12.kuikr.com/is/a/c/880x425/gallery_images/original/cf6164242661cab.gif",
    },
    {
      id: 30,
      status: "Ready to Move",
      name: "Edge Expert Oasis",
      location: "Sector 88A, Gurugram",
      type: "2 & 3 BHK Apartments",
      price: "₹ 1.3 Cr* Onwards",
      details: ["Resort-Themed Living", "Rooftop Garden", "Modern Gym"],
      image: "https://housivity-production.s3.ap-south-1.amazonaws.com/production/media/sellers/67bd7d932ca6147d3d9e9e3e/properties/67bd8787ff324ec7106f87f7/media/aa06424a-fe86-4d87-8806-279ec577a522",
    },
    {
      id: 31,
      status: "Under Construction",
      name: "Edge Expert Summit",
      location: "Sector 104, Gurugram",
      type: "3 & 4 BHK Residences",
      price: "₹ 2.1 Cr* Onwards",
      details: ["Large Central Park", "High-Rise Towers", "Modern Interiors"],
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaikCxzFqm-1_0vxdvYSuE-9MIUbGHB-L_qg&s",
    },
    {
      id: 32,
      status: "Ready to Move",
      name: "Edge Expert Frontier",
      location: "Sector 80, Gurugram",
      type: "2, 3 & 4 BHK Apartments",
      price: "₹ 1.9 Cr* Onwards",
      details: ["Panoramic Views", "Close to NH8", "Luxurious Interiors"],
      image: "https://www.buyindiahomes.com/public/uploads/properties/276/20200304033129_Mantri-VantagecityT.jpg",
    },
  ],
};
