// src/components/projects/ProjectsData.jsx
const projectsData = [
  // 🌟 Featured Developer Projects
  {
    id: 101,
    title: "Godrej City Panvel (Godrej Properties)",
    developer: "Godrej Properties",
    city: "Mumbai",
    location: "Panvel, Navi Mumbai",
    type: "2, 3 & 4 BHK",
    status: "New Project Launch",
    budget: "INR 85L - 3.5Cr",
    category: "Residential",
    rating: 4.9,
    description: "Godrej City Panvel is a sprawling 100+ acre mega golf township with world-class clubhouse, grand amenities, and rapid airport connectivity.",
    link: "https://www.godrejs-citypanvel.net/",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Golf Course", "Grand Clubhouse", "Swimming Pool", "Kids Play Area"],
    specs: { bedrooms: "2-4", bathrooms: "2-4", area: "650 - 1850 sq.ft", parking: "Covered" },
  },
  {
    id: 102,
    title: "JP Infra - North Garden City",
    developer: "JP Infra",
    city: "Mumbai",
    location: "Mira Road, Mumbai",
    type: "1, 2 & 3 BHK",
    status: "Ready to Move & Upcoming",
    budget: "INR 65L - 1.8Cr",
    category: "Residential",
    rating: 4.8,
    description: "JP North Garden City in Mira Road offers contemporary high-rise towers with 16 themed gardens, 3 grand clubhouses, and seamless WEH access.",
    link: "https://www.jpinfra.com/",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    amenities: ["16 Themed Gardens", "3 Grand Clubhouses", "Olympic Pool", "Gym & Spa"],
    specs: { bedrooms: "1-3", bathrooms: "1-3", area: "450 - 1250 sq.ft", parking: "Multi-level" },
  },
  {
    id: 103,
    title: "Sonam Group - Indralok & Beverly Park",
    developer: "Sonam Group",
    city: "Mumbai",
    location: "Mira Bhayandar, Mumbai",
    type: "2 & 3 BHK",
    status: "New Launch",
    budget: "INR 75L - 2.2Cr",
    category: "Residential",
    rating: 4.7,
    description: "Sonam Group presents prime residential towers in Mira-Bhayandar with expansive open green spaces, high quality finishes, and family-friendly living.",
    link: "https://sonamgroup.com/",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Landscaped Gardens", "Community Hall", "Children Park", "24/7 Security"],
    specs: { bedrooms: "2-3", bathrooms: "2-3", area: "680 - 1400 sq.ft", parking: "Allotted" },
  },
  {
    id: 104,
    title: "Mahindra Lifespaces - Roots & Happinest",
    developer: "Mahindra Lifespaces",
    city: "Mumbai",
    location: "Kandivali, Mumbai",
    type: "2, 3 & 4 BHK",
    status: "Upcoming Project",
    budget: "INR 1.2 - 4.5Cr",
    category: "Residential",
    rating: 4.9,
    description: "Mahindra Lifespaces creates green, sustainable luxury communities featuring IGBC platinum certified homes, Miyawaki forests, and biometric security.",
    link: "https://www.mahindralifespaces.com/",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    amenities: ["IGBC Certified", "Miyawaki Forest", "Sky Lounge", "EV Charging"],
    specs: { bedrooms: "2-4", bathrooms: "2-4", area: "750 - 2100 sq.ft", parking: "Reserved" },
  },
  // 🏠 Residential Projects
  {
    id: 1,
    title: "Edge Expert Skyshore Residences",
    city: "Pune",
    type: "2BHK",
    status: "Upcoming Project",
    budget: "INR 1 - 5Cr",
    category: "Residential",
    image:
      "https://i.pinimg.com/1200x/dd/e7/11/dde711b69812bac9d0cbdd92d3cf2c22.jpg",
  },
  {
    id: 2,
    title: "Edge Expert Hillcrest Heights",
    city: "Gurugram",
    type: "3BHK",
    status: "New Project Launch",
    budget: "INR 50L - 1Cr",
    category: "Residential",
    image:
      "https://i.pinimg.com/1200x/43/01/04/430104f16ef87c2cdc06d27767a966a9.jpg",
  },
  {
    id: 3,
    title: "Edge Expert Azure Vista",
    city: "Mumbai",
    type: "4BHK",
    status: "Upcomming Project",
    budget: "INR 1 - 5Cr",
    category: "Residential",
    image:
      "https://i.pinimg.com/1200x/e9/f4/45/e9f445b5d8f2df1eea95987776b7ce1e.jpg",
  },
  {
    id: 4,
    title: "Edge Expert Eternal Palms",
    city: "Pune",
    type: "2BHK",
    status: "New Project Launch",
    budget: "INR 80L - 2Cr",
    category: "Residential",
    image:
      "https://i.pinimg.com/1200x/93/92/60/939260b9c3b58402eca686609e97ee64.jpg",
  },
  {
    id: 5,
    title: "Edge Expert Aqua Retreat",
    city: "Bengaluru",
    type: "3BHK",
    status: "New Project Launch",
    budget: "INR 1 - 3Cr",
    category: "Residential",
    image:
      "https://i.pinimg.com/1200x/3d/43/5a/3d435a79bb38a12a03b94e12203eaeb1.jpg",
  },
  {
    id: 6,
    title: "Edge Expert Regal Pavilion",
    city: "Pune",
    type: "4BHK",
    status: "New Project Launch",
    budget: "INR 2 - 6Cr",
    category: "Residential",
    image:
      "https://i.pinimg.com/1200x/59/3e/28/593e28c5be2031c99556f705bcc3630b.jpg",
  },

  // 🏢 Commercial Projects
  {
    id: 7,
    title: "Edge Expert Zenith Business Park",
    city: "Pune",
    type: "Office Spaces",
    status: "Upcoming Project",
    budget: "INR 50L - 5Cr",
    category: "Commercial",
    image:
      "https://i.pinimg.com/1200x/c9/46/14/c9461438974cde601f570ba85f587e94.jpg",
  },
  {
    id: 8,
    title: "Edge Expert Horizon Square",
    city: "Gurugram",
    type: "Upcoming Project",
    status: "Under Construction",
    budget: "INR 1 - 10Cr",
    category: "Commercial",
    image:
      "https://i.pinimg.com/736x/cf/6a/7e/cf6a7ecd584ce7fec1b32ae9c4a10bc3.jpg",
  },
  {
    id: 9,
    title: "Edge Expert Avenue 9 Corporate",
    city: "Noida",
    type: "Office Spaces",
    status: "New Project Launch",
    budget: "INR 70L - 4Cr",
    category: "Commercial",
    image:
      "https://i.pinimg.com/736x/59/4e/07/594e0771a21e51c078657404adb1ae2a.jpg",
  },
  {
    id: 10,
    title: "Edge Expert Orion Trade Center",
    city: "Mumbai",
    type: "Shops & Offices",
    status: "Upcoming Project",
    budget: "INR 1 - 5Cr",
    category: "Commercial",
    image:
      "https://i.pinimg.com/1200x/94/b9/d3/94b9d3dafbac5b1b941ffcf0ac40be9b.jpg",
  },
  {
    id: 11,
    title: "Edge Expert Platinum Plaza",
    city: "Bengaluru",
    type: "Showrooms",
    status: "Upcoming Project",
    budget: "INR 3 - 8Cr",
    category: "Commercial",
    image:
      "https://i.pinimg.com/736x/cf/c7/f5/cfc7f501b5b7baaea14e1bd975b97f90.jpg",
  },
  {
    id: 12,
    title: "Edge Expert Infinity Park",
    city: "Hyderabad",
    type: "Corporate Offices",
    status: "New Project Launch",
    budget: "INR 2 - 10Cr",
    category: "Commercial",
    image:
      "https://i.pinimg.com/736x/4e/3e/f3/4e3ef311507f35f347c1f6f6206fc7e8.jpg",
  },
];

export default projectsData;