// src/components/projects/ProjectsData.jsx
const projectsData = [
  // 🌟 Top Developer & Flagship Projects (Mumbai West Zone & Ayodhya)
  {
    id: 101,
    title: "Mahindra Roots - Luxury Eco Homes",
    developer: "Mahindra Lifespaces",
    city: "Mumbai",
    location: "Kandivali West, Mumbai",
    type: "2 & 3 BHK",
    status: "Ready to Move",
    budget: "INR 2.45Cr - 3.80Cr",
    category: "Residential",
    rating: 4.9,
    description: "Signature green-certified luxury high-rise by Mahindra Lifespaces overlooking Sanjay Gandhi National Park with 35+ premium lifestyle amenities.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    amenities: ["IGBC Gold Certified", "National Park View", "Infinity Pool", "Sky Lounge & Terrace", "EV Charging"],
    specs: { bedrooms: "2-3", bathrooms: "2-3", area: "1150 - 1650 sq.ft", parking: "Covered Podium" },
  },
  {
    id: 102,
    title: "The Ace Sky Residences",
    developer: "Ace Group",
    city: "Mumbai",
    location: "Goregaon West, Mumbai",
    type: "3 & 4 BHK",
    status: "New Project Launch",
    budget: "INR 3.10Cr - 4.95Cr",
    category: "Residential",
    rating: 4.9,
    description: "40-storey ultra-modern tower with rooftop observatory, sky infinity pool, temperature-controlled jacuzzi, and private elevator access in Goregaon West.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Rooftop Observatory", "Sky Infinity Pool", "Smart Biometric Security", "Spa & Sauna"],
    specs: { bedrooms: "3-4", bathrooms: "3-4", area: "1450 - 2400 sq.ft", parking: "Automated Valet" },
  },
  {
    id: 103,
    title: "The Sarayu - 7-Star Gated Luxury Land",
    developer: "The House of Abhinandan Lodha (HoABL)",
    city: "Ayodhya",
    location: "Sarayu Riverfront, Ayodhya",
    type: "NA Villa Plots",
    status: "Exclusive New Launch",
    budget: "INR 1.75Cr - 3.50Cr",
    category: "Residential",
    rating: 5.0,
    description: "India's most coveted 7-star palace enclave on the holy Sarayu riverfront managed by 5-star The Leela, with private helipad and temple promenade.",
    image: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=1200&q=80",
    amenities: ["The Leela Hospitality", "Private Helipad", "Riverfront Promenade", "Ayurvedic Wellness Spa"],
    specs: { bedrooms: "Plot / Villa", bathrooms: "N/A", area: "2000 - 4500 sq.ft", parking: "Private Driveway" },
  },
  {
    id: 104,
    title: "Mahindra Vivante - Western Suburbs",
    developer: "Mahindra Lifespaces",
    city: "Mumbai",
    location: "Veera Desai Road, Andheri West, Mumbai",
    type: "3 & 4 BHK",
    status: "Ready to Move",
    budget: "INR 3.85Cr - 6.20Cr",
    category: "Residential",
    rating: 4.8,
    description: "High-fashion luxury suites in Mumbai's media and entertainment hub with rooftop cocktail lounge, temperature pool, and squash courts.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Rooftop Cocktail Lounge", "Squash Court", "Private Mini Theatre", "EV Stations"],
    specs: { bedrooms: "3-4", bathrooms: "3-4", area: "1650 - 2750 sq.ft", parking: "2 Covered Slots" },
  },
  {
    id: 105,
    title: "Lodha Woods - Forest Facing Condos",
    developer: "Lodha Group",
    city: "Mumbai",
    location: "Borivali West, Mumbai",
    type: "2, 3 & 4 BHK",
    status: "Ready to Move",
    budget: "INR 2.95Cr - 5.50Cr",
    category: "Residential",
    rating: 4.9,
    description: "Surrounded by 25,000 acres of national park greens, featuring Olympic-sized heated pool, Saint Amand international concierge, and banquet lawns.",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Saint Amand Concierge", "Heated Olympic Pool", "Banquet Lawn", "Tennis Court"],
    specs: { bedrooms: "2-4", bathrooms: "2-4", area: "1250 - 2200 sq.ft", parking: "Multi-level Covered" },
  },
  {
    id: 106,
    title: "Oberoi Sky City Integrated Enclave",
    developer: "Oberoi Realty",
    city: "Mumbai",
    location: "Borivali West Link, Mumbai",
    type: "3 & 4 BHK",
    status: "Under Construction",
    budget: "INR 3.65Cr - 6.80Cr",
    category: "Residential",
    rating: 4.9,
    description: "Sprawling 25-acre integrated lifestyle township with high-end luxury mall, 5-tier clubhouse, jogging track, and direct metro connectivity.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Attached Lifestyle Mall", "Direct Metro Station", "Bowling Alley", "Olympic Swimming Pool"],
    specs: { bedrooms: "3-4", bathrooms: "3-4", area: "1550 - 2600 sq.ft", parking: "Reserved Podium" },
  },

  // 🏠 Premium Residential Listings
  {
    id: 1,
    title: "Rustomjee Seasons Sea-Facing Penthouse",
    developer: "Rustomjee Group",
    city: "Mumbai",
    location: "Carter Road, Bandra West, Mumbai",
    type: "4BHK Penthouse",
    status: "Ready to Move",
    budget: "INR 8.5Cr",
    category: "Residential",
    rating: 5.0,
    description: "Ultra-luxury penthouse with unobstructed Arabian Sea views, private rooftop wooden deck, Italian marble flooring, and private keycard elevators.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Arabian Sea View", "Private Rooftop Deck", "Private Lift", "Smart Automation"],
    specs: { bedrooms: "4", bathrooms: "5", area: "3800 sq.ft", parking: "3 Reserved Slots" },
  },
  {
    id: 2,
    title: "Ace Divino Lifestyle Condos",
    developer: "Ace Group",
    city: "Mumbai",
    location: "Malad West, Mumbai",
    type: "2 & 3BHK",
    status: "Ready to Move",
    budget: "INR 1.85Cr - 2.85Cr",
    category: "Residential",
    rating: 4.8,
    description: "Contemporary residences 3 minutes from Mindspace IT park and Infinity Mall with double-height designer lobby and clubhouse.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Mindspace Hub", "Double Height Lobby", "Gym & Spa", "Children Play Arena"],
    specs: { bedrooms: "2-3", bathrooms: "2-3", area: "980 - 1550 sq.ft", parking: "Covered" },
  },
  {
    id: 3,
    title: "Mahindra Happinest Green Living",
    developer: "Mahindra Lifespaces",
    city: "Mumbai",
    location: "Dahisar West, Mumbai",
    type: "1 & 2BHK",
    status: "Upcoming Project",
    budget: "INR 98L - 1.65Cr",
    category: "Residential",
    rating: 4.7,
    description: "Eco-friendly homes with Miyawaki urban forest, 60% open landscaped area, solar energy, and easy access to Dahisar metro station.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Miyawaki Forest", "Solar Lighting", "Metro 2 Mins", "Jogging Track"],
    specs: { bedrooms: "1-2", bathrooms: "2", area: "520 - 850 sq.ft", parking: "Allotted" },
  },
  {
    id: 4,
    title: "Ayodhya Divine Heritage City NA Plots",
    developer: "Divine Developers",
    city: "Ayodhya",
    location: "Ram Mandir Highway Corridor, Ayodhya",
    type: "NA Residential Plots",
    status: "New Project Launch",
    budget: "INR 65L - 1.20Cr",
    category: "Residential",
    rating: 4.8,
    description: "Clear-title gated NA residential plots on Ram Mandir Highway Corridor with 60ft wide roads, underground electricity, and 24/7 security.",
    image: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=1200&q=80",
    amenities: ["60ft Wide Roads", "Underground Electricity", "Temple Promenade", "Security Gates"],
    specs: { bedrooms: "Plot", bathrooms: "N/A", area: "1200 - 3000 sq.ft", parking: "Private" },
  },

  // 🏢 Commercial Flagship Projects
  {
    id: 7,
    title: "BKC Capital Corporate Tower",
    developer: "Insignia Commercial",
    city: "Mumbai",
    location: "BKC / Bandra, Mumbai",
    type: "Grade A Office Spaces",
    status: "Ready to Move",
    budget: "INR 4.5Cr - 15.0Cr",
    category: "Commercial",
    rating: 4.9,
    description: "LEED Platinum certified corporate headquarters in Mumbai's financial center with VRV central air-conditioning and multi-tier parking.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    amenities: ["LEED Platinum", "VRV Central AC", "12 High-Speed Elevators", "Conference & Dining"],
    specs: { bedrooms: "Offices", bathrooms: "6 per floor", area: "2200 - 15000 sq.ft", parking: "15+ Dedicated Slots" },
  },
  {
    id: 8,
    title: "Lotus Grandeur Commercial Hub",
    developer: "Lotus Group",
    city: "Mumbai",
    location: "Veera Desai Road, Andheri West, Mumbai",
    type: "Retail & Corporate Offices",
    status: "Ready to Move",
    budget: "INR 2.20Cr - 6.50Cr",
    category: "Commercial",
    rating: 4.8,
    description: "High footfall commercial tower in Andheri West entertainment hub with double-height lobby, modern glass facade, and high-speed elevators.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Veera Desai Hub", "High Footfall", "24/7 Power Backup", "Double Height Lobby"],
    specs: { bedrooms: "Offices / Retail", bathrooms: "4 per floor", area: "1100 - 4500 sq.ft", parking: "Podium Parking" },
  },
];

export default projectsData;