const mongoose = require("mongoose");
require("dotenv").config();

const Property = require("../models/Property");

const sampleProperties = [
  // =========================================================================
  // 1. MAHINDRA LIFESPACES — MUMBAI WEST ZONE
  // =========================================================================
  {
    title: "Mahindra Roots — Premium 2 & 3 BHK in Kandivali West",
    description: "Mahindra Roots by Mahindra Lifespaces offers thoughtfully crafted luxury residences with 35+ lifestyle amenities, panoramic views of the Sanjay Gandhi National Park, EV charging stations, and seamless connectivity to Western Express Highway and Link Road metro station.",
    location: "Kandivali West, Mumbai",
    address: "Mahindra Roots, New Link Road, Kandivali West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400067",
    price: 24500000,
    pricePerSqFt: 26500,
    propertyType: "Flat",
    transactionType: "Buy",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    area: 1150,
    carpetArea: 925,
    floor: 14,
    totalFloors: 35,
    facing: "East",
    furnishing: "Semi-Furnished",
    parking: 2,
    ageOfProperty: "New Construction",
    builderName: "Mahindra Lifespaces",
    projectName: "Mahindra Roots",
    reraNumber: "P51800016833",
    possessionDate: "Ready to Move",
    amenities: ["Swimming Pool", "Gym", "Rooftop Garden", "Clubhouse", "24/7 Security", "EV Charging", "Children Play Area", "Multipurpose Hall", "Jogging Track", "Power Backup"],
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"
    ],
    contactName: "Mahindra Lifespaces Sales",
    contactPhone: "+91 73853 27808",
    contactEmail: "sales.roots@mahindralifespaces.com",
    postedByType: "Builder",
    status: "available",
    featured: true,
    verified: true,
    latitude: 19.2064,
    longitude: 72.8427,
  },
  {
    title: "Mahindra Happinest — Modern 1 & 2 BHK in Dahisar West",
    description: "Mahindra Happinest Dahisar by Mahindra Lifespaces offers contemporary green-certified homes surrounded by lush hills. Features Miyawaki forest, multi-tier security, reflexology path, and quick access to Dahisar metro station and Western Express Highway.",
    location: "Dahisar West, Mumbai",
    address: "Off Western Express Highway, Dahisar West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400068",
    price: 9800000,
    pricePerSqFt: 18500,
    propertyType: "Flat",
    transactionType: "Buy",
    category: "Affordable",
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    area: 680,
    carpetArea: 530,
    floor: 9,
    totalFloors: 22,
    facing: "North",
    furnishing: "Unfurnished",
    parking: 1,
    ageOfProperty: "0-1 years",
    builderName: "Mahindra Lifespaces",
    projectName: "Mahindra Happinest",
    reraNumber: "P51800027788",
    possessionDate: "Dec 2026",
    amenities: ["Miyawaki Forest", "Jogging Track", "Clubhouse", "Children Play Area", "Solar Lighting", "24/7 Security", "Lift", "Fire Safety"],
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"
    ],
    contactName: "Edge Expert Mumbai West",
    contactPhone: "+91 73853 27808",
    contactEmail: "mumbai.west@edgeexpert.com",
    postedByType: "Agent",
    status: "available",
    featured: true,
    verified: true,
    latitude: 19.2504,
    longitude: 72.8596,
  },
  {
    title: "Mahindra Vivante — Ultra-Luxury 3 BHK in Andheri West",
    description: "Mahindra Vivante in Andheri West offers expansive luxury apartments designed for celebrity lifestyle. Features double-height entrance lobby, infinity edge temperature-controlled pool, sky lounge, and private elevator access right on Veera Desai Road.",
    location: "Andheri West, Mumbai",
    address: "Veera Desai Road, Andheri West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400053",
    price: 38500000,
    pricePerSqFt: 32000,
    propertyType: "Flat",
    transactionType: "Buy",
    category: "Luxury",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    area: 1450,
    carpetArea: 1180,
    floor: 18,
    totalFloors: 30,
    facing: "West",
    furnishing: "Furnished",
    parking: 2,
    ageOfProperty: "New Construction",
    builderName: "Mahindra Lifespaces",
    projectName: "Mahindra Vivante",
    reraNumber: "P51800004521",
    possessionDate: "Ready to Move",
    amenities: ["Infinity Pool", "Sky Lounge", "Concierge Service", "High Speed Elevators", "Spa & Sauna", "Gym", "24/7 Security", "Private Deck", "Italian Marble"],
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800"
    ],
    contactName: "Mahindra Luxury Realty",
    contactPhone: "+91 73853 27808",
    contactEmail: "vivante@mahindralifespaces.com",
    postedByType: "Builder",
    status: "available",
    featured: true,
    verified: true,
    latitude: 19.1363,
    longitude: 72.8277,
  },
  {
    title: "Mahindra Alcove — Nature-Inspired 2 BHK in Chandivali",
    description: "Mahindra Alcove features biophilic residences with preserved 50-year-old banyan trees, reflexology pathways, swimming pool with pool lounge, and close proximity to Powai lake, Saki Naka metro and Western Express Link.",
    location: "Chandivali, Andheri East, Mumbai",
    address: "Off JVLR, Chandivali",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400072",
    price: 17500000,
    pricePerSqFt: 21500,
    propertyType: "Flat",
    transactionType: "Buy",
    category: "Residential",
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    area: 820,
    carpetArea: 650,
    floor: 12,
    totalFloors: 24,
    facing: "East",
    furnishing: "Semi-Furnished",
    parking: 1,
    ageOfProperty: "Ready to Move",
    builderName: "Mahindra Lifespaces",
    projectName: "Mahindra Alcove",
    reraNumber: "P51800022340",
    possessionDate: "Ready to Move",
    amenities: ["Swimming Pool", "Green Park", "Gym", "Clubhouse", "Yoga Deck", "24/7 Security", "EV Charging Point"],
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"
    ],
    contactName: "Mahindra Sales Consultant",
    contactPhone: "+91 73853 27808",
    contactEmail: "alcove@mahindralifespaces.com",
    postedByType: "Builder",
    status: "available",
    featured: false,
    verified: true,
    latitude: 19.1176,
    longitude: 72.8943,
  },

  // =========================================================================
  // 2. ACE REAL ESTATE & LANDMARK DEVELOPERS (Goregaon, Malad, Borivali, Bandra)
  // =========================================================================
  {
    title: "The Ace Sky Residences — 3 & 4 BHK in Goregaon West",
    description: "The Ace by Ace Group offers ultra-modern high-rise living near SV Road and Link Road in Goregaon West. 40-storey architectural marvel featuring sky observatory, automated parking, clubhouse, and lavish sun-deck balconies.",
    location: "Goregaon West, Mumbai",
    address: "Off SV Road, Goregaon West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400104",
    price: 31000000,
    pricePerSqFt: 27000,
    propertyType: "Flat",
    transactionType: "Buy",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    area: 1320,
    carpetArea: 1050,
    floor: 21,
    totalFloors: 40,
    facing: "North-West",
    furnishing: "Semi-Furnished",
    parking: 2,
    ageOfProperty: "Under Construction",
    builderName: "Ace Group",
    projectName: "The Ace Residences",
    reraNumber: "P51800034120",
    possessionDate: "June 2026",
    amenities: ["Sky Deck", "Infinity Pool", "Clubhouse", "Automated Car Parking", "Squash Court", "Gym", "Banquet Hall", "24/7 Security"],
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"
    ],
    contactName: "Ace Real Estate Group",
    contactPhone: "+91 73853 27808",
    contactEmail: "sales@acegroupindia.com",
    postedByType: "Builder",
    status: "available",
    featured: true,
    verified: true,
    latitude: 19.1663,
    longitude: 72.8426,
  },
  {
    title: "Ace Divino Lifestyle 2 BHK — Malad West, Mumbai",
    description: "Luxury 2 BHK at Ace Divino Malad West, situated next to Mindspace IT Hub and Inorbit Mall. Designed with Italian marble, acoustic double-glazed windows, rooftop infinity deck, and smart security.",
    location: "Malad West, Mumbai",
    address: "Link Road, Mindspace, Malad West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400064",
    price: 18500000,
    pricePerSqFt: 24000,
    propertyType: "Flat",
    transactionType: "Buy",
    category: "Residential",
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    area: 890,
    carpetArea: 720,
    floor: 11,
    totalFloors: 28,
    facing: "East",
    furnishing: "Semi-Furnished",
    parking: 1,
    ageOfProperty: "Ready to Move",
    builderName: "Ace Group",
    projectName: "Ace Divino",
    reraNumber: "P51800045612",
    possessionDate: "Ready to Move",
    amenities: ["Swimming Pool", "Gym", "Rooftop Lounge", "High Speed Elevators", "Children Play Area", "24/7 Security", "Intercom", "Power Backup"],
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800"
    ],
    contactName: "Ace Sales Office",
    contactPhone: "+91 73853 27808",
    contactEmail: "divino@acegroupindia.com",
    postedByType: "Builder",
    status: "available",
    featured: true,
    verified: true,
    latitude: 19.1860,
    longitude: 72.8354,
  },
  {
    title: "Lodha Woods — Serene 3 BHK in Borivali West",
    description: "Lodha Woods in Borivali West offers an oasis of tranquility overlooking 25,000+ acres of national park forest. Features heated Olympic swimming pool, indoor sports arena, clubhouse, and private sundecks.",
    location: "Borivali West, Mumbai",
    address: "Devidas Road, Borivali West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400092",
    price: 29500000,
    pricePerSqFt: 25000,
    propertyType: "Flat",
    transactionType: "Buy",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    area: 1280,
    carpetArea: 1020,
    floor: 15,
    totalFloors: 32,
    facing: "North-East",
    furnishing: "Semi-Furnished",
    parking: 2,
    ageOfProperty: "Ready to Move",
    builderName: "Lodha Group",
    projectName: "Lodha Woods",
    reraNumber: "P51800021345",
    possessionDate: "Ready to Move",
    amenities: ["Forest Views", "Heated Swimming Pool", "Tennis Court", "Clubhouse", "Children Play Area", "24/7 Security", "Jogging Track"],
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800"
    ],
    contactName: "Lodha Sales Consultant",
    contactPhone: "+91 73853 27808",
    contactEmail: "sales.woods@lodhagroup.com",
    postedByType: "Builder",
    status: "available",
    featured: true,
    verified: true,
    latitude: 19.2307,
    longitude: 72.8567,
  },
  {
    title: "Oberoi Sky City — Grand 3 BHK in Borivali Corridor",
    description: "Oberoi Sky City spread across 25 acres with an integrated shopping mall, multi-lane bowling alley, Olympic size pool, cricket pitch, and dedicated direct access to Western Express Highway Metro.",
    location: "Borivali East / West Link, Mumbai",
    address: "Off WEH, Borivali",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400066",
    price: 36500000,
    pricePerSqFt: 29000,
    propertyType: "Flat",
    transactionType: "Buy",
    category: "Luxury",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    area: 1380,
    carpetArea: 1094,
    floor: 28,
    totalFloors: 60,
    facing: "East",
    furnishing: "Furnished",
    parking: 2,
    ageOfProperty: "New Construction",
    builderName: "Oberoi Realty",
    projectName: "Oberoi Sky City",
    reraNumber: "P51800003582",
    possessionDate: "Ready to Move",
    amenities: ["Olympic Pool", "Bowling Alley", "Squash Courts", "Mall Access", "Gymnasium", "Spa", "24/7 Concierge"],
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800"
    ],
    contactName: "Oberoi Realty Partner",
    contactPhone: "+91 73853 27808",
    contactEmail: "skycity@oberoirealty.com",
    postedByType: "Builder",
    status: "available",
    featured: true,
    verified: true,
    latitude: 19.2288,
    longitude: 72.8622,
  },
  {
    title: "Rustomjee Seasons Elite — Sea-Facing 4 BHK Penthouse in Bandra West",
    description: "Rare luxury penthouse on Carter Road, Bandra West with panoramic Arabian Sea views. Private terrace garden, imported Italian marble, private elevator landing, home automation, and 4 dedicated car parking spaces.",
    location: "Bandra West, Mumbai",
    address: "Carter Road, Bandra West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400050",
    price: 85000000,
    pricePerSqFt: 38600,
    propertyType: "Penthouse",
    transactionType: "Buy",
    category: "Luxury",
    bedrooms: 4,
    bathrooms: 4,
    balconies: 3,
    area: 2600,
    carpetArea: 2200,
    floor: 18,
    totalFloors: 18,
    facing: "West",
    furnishing: "Furnished",
    parking: 4,
    ageOfProperty: "New Construction",
    builderName: "Rustomjee Group",
    projectName: "Rustomjee Seasons Elite",
    reraNumber: "P51800007890",
    possessionDate: "Ready to Move",
    amenities: ["Arabian Sea View", "Private Terrace", "Private Lift", "Smart Home Automation", "Infinity Pool", "24/7 Concierge", "Valet Parking"],
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"
    ],
    contactName: "Edge Expert Luxury Mumbai",
    contactPhone: "+91 73853 27808",
    contactEmail: "luxury.mumbai@edgeexpert.com",
    postedByType: "Agent",
    status: "available",
    featured: true,
    verified: true,
    latitude: 19.0607,
    longitude: 72.8258,
  },
  {
    title: "Kalpataru Radiance — Elegant 3 BHK in Siddharth Nagar, Goregaon West",
    description: "Kalpataru Radiance in Goregaon West offers signature residences with large sundecks overlooking Aarey greens, multi-purpose sport courts, squash room, infinity edge pool, and luxury clubhouse.",
    location: "Goregaon West, Mumbai",
    address: "Siddharth Nagar, SV Road, Goregaon West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400104",
    price: 27500000,
    pricePerSqFt: 24500,
    propertyType: "Flat",
    transactionType: "Buy",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    area: 1210,
    carpetArea: 980,
    floor: 16,
    totalFloors: 33,
    facing: "East",
    furnishing: "Semi-Furnished",
    parking: 2,
    ageOfProperty: "1-2 years",
    builderName: "Kalpataru Group",
    projectName: "Kalpataru Radiance",
    reraNumber: "P51800000593",
    possessionDate: "Ready to Move",
    amenities: ["Infinity Pool", "Clubhouse", "Squash Court", "Gym", "Landscaped Gardens", "Children Play Area", "24/7 Security"],
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"
    ],
    contactName: "Kalpataru Sales Partner",
    contactPhone: "+91 73853 27808",
    contactEmail: "radiance@kalpataru.com",
    postedByType: "Builder",
    status: "available",
    featured: false,
    verified: true,
    latitude: 19.1620,
    longitude: 72.8390,
  },
  {
    title: "Godrej Bliss — Modern 2 BHK in Kandivali Corridor",
    description: "Godrej Bliss in Kandivali offers resort-style living with 40+ curated amenities, terrace yoga pavilion, jogging tracks, heated indoor pool, and rapid transit via Western Express Highway and Kandivali railway station.",
    location: "Kandivali, Mumbai",
    address: "Akurli Road, Kandivali",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400101",
    price: 16200000,
    pricePerSqFt: 22800,
    propertyType: "Flat",
    transactionType: "Buy",
    category: "Residential",
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    area: 750,
    carpetArea: 590,
    floor: 19,
    totalFloors: 38,
    facing: "North",
    furnishing: "Semi-Furnished",
    parking: 1,
    ageOfProperty: "Under Construction",
    builderName: "Godrej Properties",
    projectName: "Godrej Bliss",
    reraNumber: "P51800051234",
    possessionDate: "Dec 2026",
    amenities: ["Resort Pool", "Clubhouse", "Sky Lounge", "Gym", "Yoga Pavilion", "24/7 Security", "Badminton Court"],
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"
    ],
    contactName: "Godrej Sales Representative",
    contactPhone: "+91 73853 27808",
    contactEmail: "bliss@godrejproperties.com",
    postedByType: "Builder",
    status: "available",
    featured: true,
    verified: true,
    latitude: 19.2088,
    longitude: 72.8550,
  },
  {
    title: "Adani Western Heights — 4 BHK Sea View Haven in Andheri West",
    description: "Adani Western Heights near Four Bungalows, Andheri West. Iconic high-rise tower with private decks offering stunning sunset and sea views, rooftop glass swimming pool, luxury banquets, and high-speed OTIS elevators.",
    location: "Andheri West, Mumbai",
    address: "JP Road, Four Bungalows, Andheri West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400053",
    price: 52000000,
    pricePerSqFt: 34500,
    propertyType: "Flat",
    transactionType: "Buy",
    category: "Luxury",
    bedrooms: 4,
    bathrooms: 4,
    balconies: 3,
    area: 1900,
    carpetArea: 1550,
    floor: 25,
    totalFloors: 30,
    facing: "West",
    furnishing: "Furnished",
    parking: 3,
    ageOfProperty: "Ready to Move",
    builderName: "Adani Realty",
    projectName: "Adani Western Heights",
    reraNumber: "P51800000129",
    possessionDate: "Ready to Move",
    amenities: ["Rooftop Glass Pool", "Sunset Decks", "Clubhouse", "Gym", "Spa", "24/7 Security", "Private Elevator Landing"],
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800"
    ],
    contactName: "Adani Realty Luxury Desk",
    contactPhone: "+91 73853 27808",
    contactEmail: "westernheights@adanirealty.com",
    postedByType: "Builder",
    status: "available",
    featured: true,
    verified: true,
    latitude: 19.1298,
    longitude: 72.8256,
  },

  // =========================================================================
  // 3. COMMERCIAL & RENTAL REAL ESTATE IN MUMBAI WEST ZONE
  // =========================================================================
  {
    title: "Grade A Corporate Office Space — BKC / Bandra West Corridor",
    description: "Premium Grade A LEED Platinum certified commercial office in Mumbai's financial epicentre. Features double-height corporate reception, VRV air conditioning, high-speed destination control elevators, and 10 dedicated car parks.",
    location: "BKC / Bandra, Mumbai",
    address: "G-Block, BKC Corridor, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400051",
    price: 45000000,
    pricePerSqFt: 22500,
    propertyType: "Office",
    transactionType: "Buy",
    category: "Commercial",
    bedrooms: 0,
    bathrooms: 4,
    area: 2000,
    carpetArea: 1650,
    floor: 8,
    totalFloors: 16,
    facing: "North-East",
    furnishing: "Furnished",
    parking: 10,
    ageOfProperty: "New Construction",
    builderName: "Insignia Commercial",
    projectName: "BKC Capital Tower",
    reraNumber: "P51800088991",
    possessionDate: "Ready to Move",
    amenities: ["LEED Platinum Certified", "Central AC", "High Speed Lifts", "24/7 Security", "Food Court", "Conference Center", "EV Charging Station"],
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800"
    ],
    contactName: "Edge Expert Commercial",
    contactPhone: "+91 73853 27808",
    contactEmail: "bkc.commercial@edgeexpert.com",
    postedByType: "Agent",
    status: "available",
    featured: true,
    verified: true,
    latitude: 19.0657,
    longitude: 72.8687,
  },
  {
    title: "Lotus Grandeur Commercial Plaza — Veera Desai, Andheri West",
    description: "High footfall commercial retail and boutique office space in Veera Desai Road entertainment hub. Ideal for IT firms, production houses, and creative agencies.",
    location: "Andheri West, Mumbai",
    address: "Veera Desai Road, Andheri West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400053",
    price: 22000000,
    pricePerSqFt: 22000,
    propertyType: "Office",
    transactionType: "Buy",
    category: "Commercial",
    bedrooms: 0,
    bathrooms: 2,
    area: 1000,
    carpetArea: 800,
    floor: 4,
    totalFloors: 10,
    furnishing: "Semi-Furnished",
    parking: 3,
    ageOfProperty: "1-3 years",
    builderName: "Lotus Group",
    projectName: "Lotus Grandeur",
    reraNumber: "P51800044552",
    possessionDate: "Ready to Move",
    amenities: ["Central AC", "Power Backup", "CCTV Surveillance", "Reserved Parking", "Cafeteria"],
    images: [
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800",
      "https://images.unsplash.com/photo-1497215842964-222b430dc094?w=800"
    ],
    contactName: "Lotus Commercial Desk",
    contactPhone: "+91 73853 27808",
    contactEmail: "commercial@lotusgroup.com",
    postedByType: "Builder",
    status: "available",
    featured: false,
    verified: true,
    latitude: 19.1388,
    longitude: 72.8335,
  },
  {
    title: "Fully Furnished Studio Apartment / PG in Lokhandwala, Andheri West",
    description: "Designer fully furnished studio / co-living apartment in vibrant Lokhandwala Complex. Includes high-speed fiber internet, housekeeping, smart TV, AC, microwave, and 24/7 security. Perfect for media & corporate professionals.",
    location: "Andheri West, Mumbai",
    address: "Lokhandwala Complex, Andheri West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400053",
    rent: 32000,
    price: 0,
    propertyType: "PG",
    transactionType: "Rent",
    category: "PG/Co-living",
    bedrooms: 1,
    bathrooms: 1,
    area: 350,
    furnishing: "Furnished",
    amenities: ["High Speed WiFi", "AC", "Smart TV", "Housekeeping", "Power Backup", "Security", "Microwave", "Washing Machine"],
    images: [
      "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800"
    ],
    contactName: "Edge Expert Living",
    contactPhone: "+91 73853 27808",
    contactEmail: "stay@edgeexpert.com",
    postedByType: "Owner",
    status: "available",
    verified: true,
    latitude: 19.1412,
    longitude: 72.8288,
  },

  // =========================================================================
  // 4. AYODHYA REAL ESTATE INVESTMENT LANDMARK PROJECTS
  // =========================================================================
  {
    title: "The Sarayu by HoABL — Luxury 7-Star Gated Land in Ayodhya",
    description: "Iconic 7-star palace enclave situated on the banks of holy Sarayu River in Ayodhya by The House of Abhinandan Lodha. 100% clear titled luxury NA villa plots with 5-star hotel management by The Leela, helipad, ayurvedic wellness center, and private river promenade.",
    location: "Sarayu Riverfront, Ayodhya",
    address: "The Sarayu Enclave, Guptar Ghat Road, Ayodhya",
    city: "Ayodhya",
    state: "Uttar Pradesh",
    pincode: "224001",
    price: 17500000,
    pricePerSqFt: 8750,
    propertyType: "Plot",
    transactionType: "Buy",
    category: "Luxury",
    area: 2000,
    carpetArea: 2000,
    facing: "East",
    parking: 2,
    builderName: "The House of Abhinandan Lodha (HoABL)",
    projectName: "The Sarayu Ayodhya",
    reraNumber: "UPRERAPRJ654321",
    possessionDate: "March 2027",
    amenities: ["5-Star Hotel by The Leela", "Helipad", "Private River Promenade", "Clubhouse", "Ayurvedic Wellness Spa", "Gated Security", "24/7 Concierge"],
    images: [
      "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800"
    ],
    contactName: "HoABL Ayodhya Sales",
    contactPhone: "+91 73853 27808",
    contactEmail: "ayodhya@hoabl.in",
    postedByType: "Builder",
    status: "available",
    featured: true,
    verified: true,
    latitude: 26.7922,
    longitude: 82.1998,
  },
  {
    title: "Ayodhya Divine Heritage City — Premium NA Villa Plots",
    description: "High-return commercial & residential NA plots near Ram Mandir and Maryada Purushottam Shri Ram International Airport, Ayodhya. Ideal for boutique hotels, luxury homestays, and holiday villas with 60ft wide roads, underground electricity, and grand entrance arch.",
    location: "Ram Mandir Highway Corridor, Ayodhya",
    address: "Lucknow-Ayodhya National Highway, Near Airport, Ayodhya",
    city: "Ayodhya",
    state: "Uttar Pradesh",
    pincode: "224123",
    price: 6500000,
    pricePerSqFt: 4333,
    propertyType: "Plot",
    transactionType: "Buy",
    category: "New Project",
    area: 1500,
    carpetArea: 1500,
    facing: "North-East",
    parking: 1,
    builderName: "Divine City Infra",
    projectName: "Ayodhya Divine Heritage",
    reraNumber: "UPRERAPRJ987654",
    possessionDate: "Ready to Move",
    amenities: ["Gated Township", "60ft Wide Roads", "Solar Street Lights", "Temple Complex", "Clubhouse", "Landscaped Gardens", "24/7 Security"],
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800"
    ],
    contactName: "Ayodhya Heritage Real Estate",
    contactPhone: "+91 73853 27808",
    contactEmail: "ayodhya.divine@edgeexpert.com",
    postedByType: "Agent",
    status: "available",
    featured: true,
    verified: true,
    latitude: 26.7644,
    longitude: 82.1432,
  },
];

const seedProperties = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ Connected to MongoDB");

    // Clear existing properties
    await Property.deleteMany({});
    console.log("🗑️  Cleared old properties");

    // Insert sample properties
    const created = await Property.insertMany(sampleProperties);
    console.log(`🎉 Seeded ${created.length} Mumbai West & Ayodhya properties successfully!`);

    // Summary
    const categories = {};
    const cities = {};
    created.forEach((p) => {
      categories[p.category] = (categories[p.category] || 0) + 1;
      cities[p.city] = (cities[p.city] || 0) + 1;
    });
    console.log("\n📊 Category Breakdown:");
    Object.entries(categories).forEach(([cat, count]) => {
      console.log(`   ${cat}: ${count}`);
    });
    console.log("\n🏙️ City Breakdown:");
    Object.entries(cities).forEach(([city, count]) => {
      console.log(`   ${city}: ${count}`);
    });

    process.exit(0);
  } catch (error) {
    console.error("❌ Seed error:", error.message);
    process.exit(1);
  }
};

seedProperties();
